import { UserAccount } from "../types";

export const DEFAULT_USERS: UserAccount[] = [
  {
    id: "usr-001",
    login: "admin",
    name: "Екатерина Администратор",
    firstName: "Екатерина",
    lastName: "Администратор",
    email: "admin@company.com",
    network: "Центральный Офис (Кишинёв)",
    position: "Главный Администратор",
    role: "admin",
    status: "active",
    createdAt: "2026-01-15",
  },
  {
    id: "usr-002",
    login: "manager",
    name: "Иван Руководитель",
    firstName: "Иван",
    lastName: "Руководитель",
    email: "manager@company.com",
    network: "Сеть Orange (Молдова)",
    position: "Директор по качеству",
    role: "manager",
    status: "active",
    createdAt: "2026-02-01",
  },
  {
    id: "usr-003",
    login: "auditor",
    name: "Алексей Инспектор",
    firstName: "Алексей",
    lastName: "Инспектор",
    email: "auditor@company.com",
    network: "Филиал №1 (Кишинев)",
    position: "Ведущий аудитор Mystery Shopper",
    role: "inspector",
    status: "active",
    createdAt: "2026-02-10",
  },
  {
    id: "usr-004",
    login: "shopper",
    name: "Мария Шоппер",
    firstName: "Мария",
    lastName: "Шоппер",
    email: "shopper@company.com",
    network: "Тайный Покупатель",
    position: "Контрольный покупатель",
    role: "shopper",
    status: "active",
    createdAt: "2026-03-01",
  },
];
